service: webdevtalk # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get
